test_description: 'test that stdout mismatch (with in/out match) causes failure, creates stdout.txt and does not create working/ folder'
command: 'python3 ../../../blackbox_tester.py bbtests_examples'
